### ISSUE TITLE
 Error: Requested operation is not valid: network is not running

### ISSUE THREAD

**Issue by remotejob** [rgl/terraform-libvirt-talos#2]
│ Error: Requested operation is not valid: network is not running
│
│   with libvirt_domain.controller[0],
│   on libvirt.tf line 43, in resource "libvirt_domain" "controller":
│   43: resource "libvirt_domain" "controller" {
│
╵
╷
│ Error: Requested operation is not valid: network is not running
│
│   with libvirt_domain.worker[0],
│   on libvirt.tf line 76, in resource "libvirt_domain" "worker":
│   76: resource "libvirt_domain" "worker" {

**Comment by remotejob** [comment]
Interesting. Stange but it works!

**Comment by rgl** [comment]
It does? Either way, not sure why that's happening. Maybe ask about this in a discussion at the terraform libvirt provider repository.
